theme: jekyll-theme-cayman
permalink: /:categories/:year/:month/:day/:title:output_ext
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
